<?php
/**
 * @file
 * variable.field_bundle_settings_node__faq.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_node__faq',
  'content' => array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(
        'detailed_question' => array(
          'weight' => '1',
        ),
        'title' => array(
          'weight' => '0',
        ),
        'path' => array(
          'weight' => '2',
        ),
      ),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
