<?php

/**
 * Implements hook_install().
 */
function og_credit_install() {
  // Add the OG Credit field to the OG entities/bundles
  $entities_bundles = og_get_all_group_bundle(); // Bundles nested in entity arrays
  _field_info_collate_fields(TRUE);
  _field_info_collate_types(TRUE);
  foreach ($entities_bundles as $entity_type=>$bundles) {
    foreach ($bundles as $bundle=>$bundle_title) {
        og_credit_addfield($entity_type, $bundle);
    }
  }
}
